name: PR CI

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

env:
  CI_USER: cryostat+bot
  CI_REGISTRY: quay.io/cryostat
  CI_IMG: quay.io/cryostat/cryostat-storage
  REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
  REF: ${{ github.event.pull_request.head.ref }}

jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Checkout PR code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Build container image
      id: buildah-build
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
      with:
        image: ${{ env.CI_IMG }}
        archs: amd64
        tags: pr-ci
        containerfiles: |
          ./Dockerfile

  test:
    needs: pr_build
    uses: ./.github/workflows/test-cryostat.yml
    with:
      java-version: '25'
      storage-image-tag: pr-ci
