name: PR CI

concurrency:
  group: ci-${{ github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

env:
  CI_USER: cryostat+bot
  CI_REGISTRY: quay.io/cryostat
  CI_IMG: quay.io/cryostat/cryostat-storage
  REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
  REF: ${{ github.event.pull_request.head.ref }}

jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Checkout PR code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Build container image
      id: buildah-build
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2
      with:
        image: ${{ env.CI_IMG }}
        archs: amd64
        tags: pr-ci
        containerfiles: |
          ./Dockerfile
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: ${{ github.repository_owner }}/cryostat
        ref: main
        submodules: true
        fetch-depth: 0
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - run: git submodule init && git submodule update
    - name: Cache yarn packages
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: "./src/main/webui/.yarn/cache"
        key: ${{ runner.os }}-build-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-yarn-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Initialize web assets
      run: |
        cd src/main/webui
        yarn install && yarn yarn:frzinstall
        cd -
    - name: Add CRIU PPA
      run: sudo add-apt-repository ppa:criu/ppa && sudo apt update
    - name: Install podman v4
      run: |
        sudo apt -y purge podman
        sudo apt -y update && sudo apt -y satisfy "podman (>= 4.0), podman-docker"
    - name: Start Podman API
      run: systemctl --user enable --now podman.socket
    - name: Set DOCKER_HOST environment variable
      run: echo "DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock" >> "$GITHUB_ENV"
    - name: Run unit tests
      uses: Wandalen/wretry.action@v3.8.0
      env:
        CRYOSTAT_STORAGE_VERSION: pr-ci
      with:
        attempt_limit: 3
        command: |
          ./mvnw -B -U \
            -Dquarkus.hibernate-orm.log.sql=false \
            -Dquarkus.log.level=error \
            -Dquarkus.http.access-log.enabled=false \
            -Dquarkus.smallrye-graphql.log-payload=off \
            compile test > unit-test.log 2>&1
    - name: Dump unit test logs
      if: always()
      run: tail -500l unit-test.log
    - name: Upload unit test logs
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: cryostat-storage-unittest.log
        path: unit-test.log
    - name: Run integration tests
      uses: Wandalen/wretry.action@v3.8.0
      env:
        CRYOSTAT_STORAGE_VERSION: pr-ci
      with:
        attempt_limit: 3
        command: |
          ./mvnw -B -U \
            -Dquarkus.hibernate-orm.log.sql=false \
            -Dquarkus.log.level=error \
            -Dquarkus.http.access-log.enabled=false \
            -Dquarkus.smallrye-graphql.log-payload=off \
            -Dskip.surefire.tests \
            verify > integration-test.log 2>&1
    - name: Dump integration test logs
      if: always()
      run: tail -500l integration-test.log
    - name: Upload integration test logs
      uses: actions/upload-artifact@v7
      if: always()
      with:
        name: cryostat-storage-itest.log
        path: integration-test.log
